loadstring(game:HttpGet("https://pastebin.com/raw/Nv89Cn5d", true))()

-- Features:
-- Escape The Dungeon Obby
-- Escape Grandpa's House Obby
-- Escape Candyland Obby
-- Escape The Daycare Obby
-- Rob Mr Rich's Mansion Obby
-- Escape Charli D'amelio Obby
-- Escape The Cruise Ship Obby
-- Escape The Supermarket Obby
-- Escape The Dentist Obby
-- Escape Santa's Workshop Obby
-- Escape The Pic Nic Obby
-- Escape The Carnival of Terror Obby
-- Escape The Hotel Obby
-- Escape Among Us Impostor Obby
-- Easy Obby
-- Mega Easy Obby
-- Escape The Toy Room Obby
-- Escape Krusty Krab Obby
-- Escape Prison Obby
-- Escape The Minions Obby
-- Escape Baldi Mega Parkour Obby
-- Escape The Bowling Alley Obby
-- Escape Grandma's House Obby
-- Escape The Google Meet Obby
-- Escape School Obby
-- Escape The Zoom Meeting Obby
-- Horrors Parkour Obby
-- Escape The Kitchen Obby
-- Escape The Tablet Obby
-- Escape The Barber Shop Obby
-- Escape Fun Granny Obby
-- Parkour Obby
-- Escape The Bakery Obby
-- Escape The Gym Obby
-- Escape Among Us Obby
-- Escape McDonalds Obby
-- Escape The Restaurant Obby
-- PARKOUR
-- The Crazy Adventure Obby
-- Escape The Hospital Obby
-- Escape iPhone 12 Obby
-- Escape The Farm Obby