-- Anti AFK
for i,v in pairs(getconnections(game:GetService("Players").LocalPlayer.Idled)) do
v:Disable()
end

loadstring(game:HttpGet("https://raw.githubusercontent.com/1201for/V.G-Hub/main/V.Ghub", true))()

-- Features:
-- Adopt me
-- Age Of Heros
-- Arsenal
-- Assassin
-- Bad Business
-- Be Crushed by a Speeding Wall
-- Blox Fruits
-- Break-in-Story
-- Breaking Point
-- Bubble Gun Simulator
-- Build a boat
-- Car Crusher 2
-- Climb 1,000 Stairs
-- Cursed Islands
-- DemonFall
-- Destruction Simulator
-- Dragon Adventures
-- Dungeon Quest!
-- Elemental Battlegrounds
-- Elemental Legends
-- Field Trip Z
-- GreenVile
-- Jailbreak
-- KAT
-- Knife Simulator
-- Legends Of Speed
-- Little World
-- MM2
-- Magnet Simulator
-- Meep City
-- Mega Easy Obby
-- Muscle Legends
-- Natural Disaster Survival
-- Ninja Legends
-- Ninja Legends 2
-- Phantom Forces
-- Project Lazarus:ZOMBIES
-- Project XL
-- Ragdoll Engine
-- Shindo
-- SHOOT OUT!
-- Soda Champions
-- Speed Run 4
-- Super Bomb Sirvival
-- Survive The Disasters! Classic
-- Taping-Gods
-- The Asylum
-- The Floor Is LAVA
-- The Labyrinth
-- The Maze
-- Timber
-- Tower of hell
-- Trade Tower
-- TSUNAMI SURVIVAL
-- Vehicle Legends
-- Vehicle Simulator
-- Warrior Champions
-- Weaponry
-- Zombies Attack
-- Zombie Rush
-- Zombie Uprising